# BTC 15m Arena validation helpers
# Generated by BTC_15M_ARENA_VALIDATION_HELPERS_CODE_IMPLEMENTATION_V1_LOCAL_POWERSHELL_HELPER_REPAIR_V1_PARSER_SAFE_WRITER
# Purpose: shared parser-safe validators for BTC 15m Arena microphases.
# Scope: helper-only. No network calls, no wallet connection, no order logic, no runtime product code.

Set-StrictMode -Version Latest

function Normalize-Btc15mArray {
    param([object]$Value)

    if ($null -eq $Value) {
        return @()
    }

    if ($Value -is [System.Array]) {
        return @($Value)
    }

    return @($Value)
}

function Get-Btc15mSafeCount {
    param([object]$Value)

    if ($null -eq $Value) {
        return 0
    }

    if ($Value -is [string]) {
        if ($Value.Length -eq 0) {
            return 0
        }

        return 1
    }

    if ($Value -is [System.Array]) {
        return $Value.Length
    }

    if ($Value -is [System.Collections.ICollection]) {
        return $Value.Count
    }

    return 1
}

function New-Btc15mValidationResult {
    param(
        [string]$Level,
        [string]$Code,
        [string]$Message,
        [object]$Evidence = $null
    )

    return [pscustomobject]@{
        level = $Level
        code = $Code
        message = $Message
        evidence = $Evidence
    }
}

function Get-Btc15mSnippet {
    param(
        [string]$Text,
        [string]$Term,
        [int]$Radius = 80
    )

    if ([string]::IsNullOrEmpty($Text)) {
        return ''
    }

    if ([string]::IsNullOrEmpty($Term)) {
        return ''
    }

    $Index = $Text.IndexOf($Term, [System.StringComparison]::OrdinalIgnoreCase)

    if ($Index -lt 0) {
        return ''
    }

    $Start = [Math]::Max(0, $Index - $Radius)
    $Length = [Math]::Min($Text.Length - $Start, $Term.Length + ($Radius * 2))
    $Snippet = $Text.Substring($Start, $Length)
    $Snippet = $Snippet -replace '\s+', ' '

    return $Snippet.Trim()
}

function Classify-Btc15mGuardrailTerm {
    param(
        [string]$Text,
        [string]$Term
    )

    $Snippet = Get-Btc15mSnippet -Text $Text -Term $Term -Radius 140

    if ([string]::IsNullOrWhiteSpace($Snippet)) {
        return [pscustomobject]@{
            term = $Term
            classification = 'ABSENT'
            snippet = ''
        }
    }

    $Lower = $Snippet.ToLowerInvariant()

    $NegatedPatterns = @(
        'no wallet',
        'no private keys',
        'no orders',
        'no real orders',
        'no orders of any kind',
        'no order execution',
        'no live data',
        'non-live',
        'before any live data',
        'without live data',
        'no authenticated trading api',
        'no trading automation',
        'no financial advice',
        'simulation only',
        'manual inputs',
        'manual/static',
        'paper-only',
        'does not authorize',
        'not authorize',
        'forbidden',
        'prohibited',
        'disallowed',
        'not allowed',
        'guardrail'
    )

    foreach ($Pattern in $NegatedPatterns) {
        if ($Lower.Contains($Pattern)) {
            return [pscustomobject]@{
                term = $Term
                classification = 'NEGATED_GUARDRAIL'
                snippet = $Snippet
            }
        }
    }

    $PositivePatterns = @(
        'connect wallet',
        'place order',
        'execute order',
        'orders enabled',
        'real orders enabled',
        'trading automation supported',
        'live trading mode',
        'authenticated trading api available',
        'guaranteed profit',
        'guaranteed prediction',
        'risk-free',
        'sure win',
        'buy now',
        'sell now',
        'trade now'
    )

    foreach ($Pattern in $PositivePatterns) {
        if ($Lower.Contains($Pattern)) {
            return [pscustomobject]@{
                term = $Term
                classification = 'POSITIVE_CAPABILITY_OR_CLAIM'
                snippet = $Snippet
            }
        }
    }

    return [pscustomobject]@{
        term = $Term
        classification = 'AMBIGUOUS_REQUIRES_REVIEW'
        snippet = $Snippet
    }
}

function Get-Btc15mGitScopeSnapshot {
    param([string]$RepoPath = (Get-Location).Path)

    Push-Location -LiteralPath $RepoPath

    try {
        $Branch = (git branch --show-current | Out-String).Trim()
        $Head = (git rev-parse HEAD | Out-String).Trim()
        $OriginMain = (git rev-parse origin/main | Out-String).Trim()
        $Status = @((git status --short --untracked-files=all))
        $Cached = @((git diff --cached --name-only))
        $Tracked = @((git diff --name-only))
        $Untracked = @((git ls-files --others --exclude-standard))

        return [pscustomobject]@{
            branch = $Branch
            head = $Head
            origin_main = $OriginMain
            status = @($Status)
            cached = @($Cached)
            tracked = @($Tracked)
            untracked = @($Untracked)
            status_count = (Get-Btc15mSafeCount $Status)
            cached_count = (Get-Btc15mSafeCount $Cached)
            tracked_count = (Get-Btc15mSafeCount $Tracked)
            untracked_count = (Get-Btc15mSafeCount $Untracked)
        }
    }
    finally {
        Pop-Location
    }
}

function Test-Btc15mExactScope {
    param(
        [string[]]$Actual,
        [string[]]$Expected
    )

    $ActualNormalized = @(Normalize-Btc15mArray $Actual | Sort-Object)
    $ExpectedNormalized = @(Normalize-Btc15mArray $Expected | Sort-Object)
    $ActualJoined = ($ActualNormalized -join '|')
    $ExpectedJoined = ($ExpectedNormalized -join '|')

    return [pscustomobject]@{
        pass = ($ActualJoined -eq $ExpectedJoined)
        actual = @($ActualNormalized)
        expected = @($ExpectedNormalized)
    }
}

function Test-Btc15mAnchorEvidence {
    param(
        [string]$Path,
        [string[]]$Anchors
    )

    $Results = @()

    if (-not (Test-Path -LiteralPath $Path)) {
        return [pscustomobject]@{
            pass = $false
            results = @([pscustomobject]@{
                anchor = '<file>'
                present = $false
                path = $Path
            })
        }
    }

    foreach ($Anchor in @($Anchors)) {
        $Present = Select-String -LiteralPath $Path -SimpleMatch $Anchor -Quiet
        $Results += [pscustomobject]@{
            anchor = $Anchor
            present = [bool]$Present
            path = $Path
        }
    }

    $Missing = @($Results | Where-Object { -not $_.present })

    return [pscustomobject]@{
        pass = ((Get-Btc15mSafeCount $Missing) -eq 0)
        results = @($Results)
    }
}

function Normalize-Btc15mPublicSmokeResponse {
    param(
        [object]$Response,
        [string]$RequestedUrl
    )

    $StatusCode = $null
    $FinalUrl = ''
    $Content = ''
    $Warnings = @()

    if ($null -ne $Response) {
        if ($Response.PSObject.Properties.Name -contains 'StatusCode') {
            $StatusCode = $Response.StatusCode
        }

        if ($Response.PSObject.Properties.Name -contains 'Content') {
            $Content = [string]$Response.Content
        }

        try {
            if ($null -ne $Response.BaseResponse -and $null -ne $Response.BaseResponse.ResponseUri) {
                $FinalUrl = [string]$Response.BaseResponse.ResponseUri.AbsoluteUri
            }
        }
        catch {
            $FinalUrl = ''
        }
    }

    if ([string]::IsNullOrWhiteSpace($FinalUrl)) {
        $Warnings += 'FINAL_URL_UNAVAILABLE_NON_BLOCKING_IF_STATUS_AND_CONTENT_PASS'
        $FinalUrl = $RequestedUrl
    }

    return [pscustomobject]@{
        requested_url = $RequestedUrl
        final_url = $FinalUrl
        status_code = $StatusCode
        content = $Content
        warnings = @($Warnings)
    }
}

function New-Btc15mParserSafePhaseTemplate {
    param([string]$PhaseName)

    $Lines = @()
    $Lines += '# ' + $PhaseName
    $Lines += '$OutputPath = Join-Path $env:USERPROFILE ''Downloads\outputs.txt'''
    $Lines += 'Start-Transcript -LiteralPath $OutputPath -Force'
    $Lines += 'Write-Output ''PHASE=' + $PhaseName + ''''
    $Lines += 'Write-Output ''NO_STAGE_NO_COMMIT_NO_PUSH=true'''
    $Lines += 'Stop-Transcript'
    $Lines += 'Write-Output (''OUTPUT_FILE='' + $OutputPath)'

    return @($Lines)
}
